### PR TITLE
Merge in Paulmillr master

### PR DESCRIPTION
**Pull request by ckcollab**

### CODE REVIEW

**Comment by ckcollab** [comment]
Woops my bad steven meant to do this on my dotfiles repo!

**Comment by skoczen** [comment]
@ckcollab Hah, all good!  Hello, by the way!    How goes it?

**Comment by ckcollab** [comment]
Heyo! It's going alright, taking a little sabbatical to re-find some motivation :)

Levi mentioned a couple weeks ago that you are adventuring around the world... that's nuts! Hope everything's going well. How're you doin?

**Comment by skoczen** [comment]
Hey man, 

I hear that - hope motivation finds you!   Still doing the chin-up stuff?

Levi tells the story right - I sold everything, bought a one-way ticket, and started writing a letter every week.  You can follow along if you're so inclined here: http://inkandfeet.com  :)

**Comment by ckcollab** [comment]
I was keeping chin up stats diligently up until a few weeks ago when I ran out of space on the Heroku db and I've been working on a replacement called "mean coach" :) Actually did a little machine learning voodoo to predict how my next day was going to go and it ended up being pretty accurate. It's a pretty simple problem predicting what the next 1-10 will be, but it was fun stuff!

Also, totally subscribed.

Have a good one!

**Comment by skoczen** [comment]
That's super cool - is mean coach open-sourced / going to be more widely available?

**Comment by ckcollab** [comment]
Yeah it's [open source](https://github.com/dev-coop/meancoach)! I started it at the Dev-Coop I'm sure Levi has told ya about

It was meant to be a text messaging based mean coach but I got lazy and focused on the wrong details. Should definitely get it in a nicer state. Mostly messed around with Heroku one click deploy, bower/node package management, stylus, and a [dash](https://github.com/dev-coop/meancoach/blob/master/meancoach_project/apps/metrics/static/riot/metric_record_form.tag) of [RiotJS](http://riotjs.com/). Looking back it's pretty convoluted, experiencing that trying to re-set it up on my machine... something with stylus seems busted :-1: 

Btw saw change monsters from your recent update, I think that's a pretty cool idea. I definitely have more than a few mental patterns I'm trying to re-program. What is it all about? Is there a Will bot involved?! :)

**Comment by skoczen** [comment]
Nice!   Haven't heard about the dev-coop, but sounds cool! 

What did you think of RiotJS?  Have been meaning to play with it and see, wuold love some thoughts.

Change Monsters is a cross between a bot, an app, and a book.  Automated email/text/push support, new content every day, and a guided course for people to go after their big dreams.  It's been through alpha, is in beta now.  Excited.

**Comment by ckcollab** [comment]
RiotJS was pretty cool, I was pretty confused when it came to actually pulling data in and distributing it from parent -> children in a nice way. Then after I finished I learned about FLUX/using a common store and that seems to make some sense but I haven't noodled with it too much yet. It's also a super tiny/minimalist library so you'll probably want a couple other things to compliment it like q for promises (IIRC, been a while, may have promises now).

Awesome about Change Monsters, can't wait to hear more about it/some case studies in your newsletters :)

**Pull request closed without merging**
